# Generated by Django 3.2.4 on 2021-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.CharField(max_length=60)),
                ('supplier_name', models.CharField(max_length=45)),
                ('req_item_name', models.CharField(max_length=45)),
                ('req_item_quantity', models.PositiveIntegerField()),
                ('date_of_order_received', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=45)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Not available', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=45)),
                ('item_name', models.CharField(max_length=45)),
                ('item_type', models.CharField(max_length=60)),
                ('item_available_quantity', models.PositiveIntegerField()),
                ('item_price', models.PositiveIntegerField()),
            ],
        ),
    ]
